
def initialize(): 
    #NOT SURE WHAT GOES HERE BUT HAVE TO THOUGHTS
    #1. COULD BE WERE WE DO SOMTHING LIKE DC OR AC INTIALIZATION AND GET FIRST V VECTOR GUESS
    # 2.WHERE WE CALL EACH OBJECT AND ASSING THE NODED INDEXES  

    
    pass